# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy master branch

on:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Commit telah kami terima, saat ini code terbaru akan di Deploy secara automatis ke:
            - Domain: **https://xxxxxxxxx**
            - Deploy Status: **https://github.com/<owner-name>/<repo-name>/actions**
            Anda akan menerima notifikasi jika deploy telah selesai dilakukan, harap menunggu notifikasi selanjutnya.!

  build:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  done:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Deploy sukses, anda bisa mengecek preview website di:
            - Domain: **https://xxxxxxxxx**
            - Deploy Status: **https://github.com/<owner-name>/<repo-name>/actions**

            Jika ada kendala, jangan ragu untuk menghubungi team devops.!